### PR TITLE
fix: Improve MathML for math operators with subscripts

### PR DESCRIPTION
**Pull request by ronkok**
This PR is an accessibility advance and a MathML visual regression. It relates to math operators like `\log` or `\lim` that are written with subscripts or limits.  In Issue #2593, @Futyn-Maker reports that that the `log` is omitted in three different screen readers. This PR will eliminate that problem.

In so doing, this PR will also introduce a spacing regression for visible rendering viewed in a MathML-capable browser like Firefox. This may concern you, so I'll explain why I did it.

Spacing is usually easier in MathML  than in HTML. You just put content into the proper `<mi>` or `<mo>` elements and the browser does the spacing for you. The exception is math operators like `\log` or `\lim` or anything inside an `\operatorname`. MathML has no direct analogue to a TeX math operator. MathJax puts them into a `<mi>` element, but `<mi>` elements get the  spacing of a variable, not an operator. 

To get the correct spacing, I have previously tried wrapping the `<mi>` inside an `<mo>`. That is what caused issue #2593. I also tried to skip the `<mi>` and place the text directly in an `<mo>`. That caused Firefox to improperly display `\lim\limits`, i.e. MathML `<munder>` element, as if it were a subscript, not a limit. So that does not work either.

So I believe the math operator has to be in a `<mi>` with no `<mo>`. That's the way to enable screen readers to work properly. That is what this PR does.

There is a way to regain proper visual spacing. On the HTML side, the `buildHTML.traverseNonSpaceNodes()` function makes a pass through the HTML and inserts hard spacing elements where necessary. Such a thing could also be done on the MathML side. It might be slightly easier in MathML because spacing elements would be necessary only adjacent to math operators. MathML takes care of the other spacing issues.

Easy or not, it's more than I have time to do right now. I think we should get this accessibility fix into the next release and deal with the visible spacing later.

### CODE REVIEW

**Comment by ronkok** [comment]
We now have [confirmation](https://github.com/KaTeX/KaTeX/issues/2593#issuecomment-710767752) that this PR fixes the accessibility problem.

**Comment by kevinbarabash** [comment]
@ronkok thanks for fixing the accessibility issue.  I'm not to concerned about the visual regression.  I think it might be fixable with some CSS, but I'll have to investigate that and we don't really use much CSS with our MathML.

**Review by kevinbarabash — APPROVED** [review]
Thanks for fixing this.  The change looks reasonable especially given the changes to the snapshots.  I wish we had more MathML snapshots though since I think our coverage in this area is that good.  I'll spend some time later figuring out what snapshots to add, but this PR can go forward as is.

**Comment by kevinbarabash** [comment]
Since this only makes changes to a `mathmlBuilder` function I think it's safe to merge even if we don't hear back from the Safari screenshotter.

**Comment by Futyn-Maker** [comment]
Many thanks for fixing this problem and sorry for my long silence, I was really busy in last days.

Andrey

**Pull request merged**
