### PR TITLE
Release v0.13.0

### PR DESCRIPTION
**Pull request by kevinbarabash**
I looked at the changes since the v0.12.0 release and didn't spot any breaking changes, but I figured since there were quite a few changes that maybe it warranted a minor version bump (as opposed to a patch bump).

### CODE REVIEW

**Comment by ronkok** [comment]
I think we should merge PR #2712 before a release. As is, all those new AMS environments will write a parse error given default rendering options.

**Comment by ronkok** [comment]
Does KA still load MathJax as a backup? After this release, it should try to do without.

**Comment by kevinbarabash** [comment]
@ronkok it does unfortunately.  We're still on 0.11.x.  I'm sure we'll upgrade at some point in the new year at which point we'll test all of our content against the new version to see if we still need the MathJax fallback.

**Comment by kevinbarabash** [comment]
I'm going to close this and will recreate it once #2712 has been reviewed and merged.

**Comment by ronkok** [comment]
@kevinbarabash Is there any reason not to release v0.13.0?

**Comment by ChrisZieba** [comment]
Does anyone happen to know if there are any pending tasks before a `0.13` release? I see that https://github.com/KaTeX/KaTeX/pull/2712 got merged, should I add a new release PR?

**Comment by kevinbarabash** [comment]
@ronkok not that I'm aware of.  @ChrisZieba while you could create a release PR you won't be able to do the publish and I don't think we've ever tried the release process with multiple people doing different parts of it.

**Comment by kevinbarabash** [comment]
I've created a new PR for the 0.13.0 release, see #2824.

**Comment by ice1000** [comment]
> I looked at the changes since the v0.12.0 release and didn't spot any breaking changes, but I figured since there were quite a few changes that maybe it warranted a minor version bump (as opposed to a patch bump).

Is there a changelog?

**Comment by ronkok** [comment]
@ice1000 Yes, you'll want to look at both the [release notes](https://github.com/KaTeX/KaTeX/releases) and this release's [migration guide](https://github.com/KaTeX/KaTeX/issues/2490).

**Comment by ice1000** [comment]
Thanks!

**Pull request closed without merging**
