### PR TITLE
Suggest <!DOCTYPE html> in documentation

### PR DESCRIPTION
**Pull request by edemaine**
The documentation currently doesn't mention `<!DOCTYPE>` at all.  Inspired by #2047.

### CODE REVIEW

**Comment by ylemkimon** [comment]
[The starter template on the README](https://github.com/KaTeX/KaTeX#starter-template) mentions it. Maybe should we include it in the main page or documentation?

**Comment by edemaine** [comment]
@ylemkimon Good idea! I've added the starter template to `docs/browser.md`, in place of the DOCTYPE warning.  (There's still a DOCTYPE warning in Common Issues, which seems appropriate.)  Also fixed a few things in the wording of that document.

**Comment by kevinbarabash** [comment]
In the case of #2047 the specific issue was that iframes don't inherit the DOCTYPE so it needs to be set there as well.  Perhaps we should specifically mention iframes.

**Comment by edemaine** [comment]
@kevinbarabash Good idea.  I've [added a mention](https://github.com/KaTeX/KaTeX/pull/2052/commits/86c95095c04e225b07ba30413e386f3d3b755a64).

In [my latest commit](https://github.com/KaTeX/KaTeX/pull/2052/commits/06e95540720e55410bfe9401f0653eea3c139182), I also changed the default docs page to https://katex.org/docs/browser.html instead of https://katex.org/docs/node.html, because I feel like this is a more useful starting point for a novice.  But if anyone disagrees, I am happy to undo that change.

**Comment by kevinbarabash** [comment]
@edemaine thanks.  @ylemkimon thanks for reviewing.

**Pull request merged**
