### PR TITLE
feat: Set Auto-render to recognize AMS environments without $$…$$ delimiters.

### PR DESCRIPTION
**Pull request by ronkok**

### CODE REVIEW

**Comment by kevinbarabash** [comment]
I haven't reviewed #2679, but I think there might be a conflict between this PR and that one.  Hopefully it won't be too hard to resolve.

**Comment by ronkok** [comment]
I tried to write this PR in a way that would avoid a conflict with #2679. I hope I succeeded.

**Comment by ronkok** [comment]
The merge conflict in this PR is resolved. It's ready to go.

**Review by kevinbarabash — COMMENTED** [review]
Thanks for the PR.  It's nice that people will be able to use `align`, `equation`, etc. in their documents while avoiding having to deviate from LaTeX's handling of math mode.

It looks like `renderMathInText` doesn't actually use the environment delimiters when rendering the math. As a result, the content between these delimiters doesn't get rendered within that environment which is what I was expect to happen.

**Comment by ronkok** [comment]
Well, that was embarrassing. Fixed now.

**Review by kevinbarabash — APPROVED** [review]
LGTM. 🎉

**Comment by edemaine** [comment]
Congrats, this is awesome! As it's one of the most requested features I've heard of KaTeX ("where's align?"), we should think about a release soon

**Comment by kevinbarabash** [comment]
It would be nice to get the pending `fix` PRs reviewed before a release.

**Pull request merged**
