### PR TITLE
chore: enable Gitpod

### PR DESCRIPTION
**Pull request by ylemkimon**
> This commit implements a fully-automated development setup using Gitpod.io, an online IDE for GitHub and GitLab that enables Dev-Environments-As-Code. This makes it easy for anyone to get a ready-to-code workspace for any branch, issue or pull request almost instantly with a single click.

Example: https://gitpod.io/#https://github.com/KaTeX/KaTeX/tree/gitpod

Gitpod

### CODE REVIEW

**Comment by kevinbarabash** [comment]
This looks really cool.  Do you know how this compares to https://github.com/features/codespaces/?  I have to admit I haven't a chance to try either of these tools out. 😅

**Comment by ylemkimon** [comment]
@kevinbarabash I've signed up for beta about a month ago, but no news 😢 Looking at [tweets](https://twitter.com/search?q=github%20codespaces), it seems awesome.

**Comment by ylemkimon** [comment]
@kevinbarabash Another feature I'm looking forward to is [GitHub Discussions](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions). I know there are many questions regarding KaTeX on the Gitter chat and StackOverflow, but I didn't have chance to look at them.

**Comment by kevinbarabash** [comment]
The fact that it supports threading seems like a big win over Gitter (not to mention the co-location).

**Comment by ylemkimon** [comment]
@kevinbarabash I've asked to get us in the beta for Discussions in [the GitHub community post](https://github.community/t/can-one-apply-for-github-discussions-beta/121120/53), and we're in!

**Pull request merged**
