### PR TITLE
Support MathML display mode

### LINKED ISSUE #2219: Display mode doesn't work for MathML output
**Describe the bug:**
Display mode does not work for MathML output (it does for HTML output).

**To Reproduce:**
Render any expression, using the options `{displayMode: true, output: 'mathml'}`.
See [JSFiddle](https://jsfiddle.net/2b497Ls0/).

**Expected behavior:**
Expression renders in display mode, i.e.&nbsp;display-style math centred on its own line.

**Actual behavior:**
Expression appears to render in inline mode.

**Screenshot:**

**Environment:**
 - KaTeX Version: 0.11.1
 - Browser: any browser which supports MathML

### PR DESCRIPTION
**Pull request by ronkok**
Fix #2219.

### CODE REVIEW

**Comment by ronkok** [comment]
Below is visual evidence (from Firefox) that this PR fixes the problem. This comes from the code:
```
<p>\(\sum_{i=0}^{100}x^2\)</p>
<p>\[\sum_{i=0}^{100}x^2\]</p>
```

DisplayMML

There are also two tests in the MathML snapshots.

**Comment by ronkok** [comment]
@ylemkimon Thank you for the review!

**Comment by phpdev1995** [comment]
is katex convert `MathML to mathematics formulas` ? like mathjax

**Comment by kevinbarabash** [comment]
@ronkok thanks for adding snapshots!  The display rendering of the sigma feels a little over the top.  Do you know if browsers that support MathML will render it using a different font if the font has a `MATH` table in it?

**Comment by ronkok** [comment]
I believe that MathML-capable browsers will allow CSS to set a font for the `<math>`. If the webpage CSS makes no declaration, then the browser picks a system font. The screenshot in my comment above used the Cambria Math font installed on my machine.

**Pull request merged**
