### PR TITLE
fix: `\vdots` support in text mode

### LINKED ISSUE #3990: \text{⋮} causes error message
\text{⋮} will cause an error message:
KaTeX parse error: Can't use function '\mathord' in text mode at position 1: \̲m̲a̲t̲h̲o̲r̲d̲{\varvdots\rule…
other ellipsis unicode characters seem to work fine.

### PR DESCRIPTION
**Pull request by pzinn**
Fixes #3990 following @ronkok instructions.
Incidentally, what's up with all the open PRs requiring reviews?
edited: I see, 1 review needed for automatic merging...

### CODE REVIEW

**Review by edemaine — APPROVED** [review]
Sorry for the delay. I wanted to confirm that `\vdots` actually works in LaTeX in text mode. It does! Here's the behavior I observe in LaTeX:

* `\dots`, `\ldots`, and `\vdots` all seem to work in both text mode and math mode
* `\cdots` works in math mode only

KaTeX has the same behavior *except* for `\vdots` in text mode, which this PR fixes. Nice!

I have some changes I'd like to make to this PR to clean it up some, though. It looks like "Maintainers are allowed to edit this pull request" is turned on but I can't push to it, perhaps because your PR is from your `main` branch and the `main` branch is protected? Could you unprotect `main` in your fork?

Here's what I aim to add: `Unify math and text \vdots, allow \rule in text mode`

```diff
diff --git a/src/functions/rule.js b/src/functions/rule.js
index 005c1ba4..1cf85ac4 100644
--- a/src/functions/rule.js
+++ b/src/functions/rule.js
@@ -11,6 +11,8 @@ defineFunction({
     props: {
         numArgs: 2,
         numOptionalArgs: 1,
+        allowedInText: true,
+        allowedInMath: true,
         argTypes: ["size", "size", "size"],
     },
     handler({parser}, args, optArgs) {
diff --git a/src/macros.js b/src/macros.js
index 949790fc..a57989f2 100644
--- a/src/macros.js
+++ b/src/macros.js
@@ -341,8 +341,7 @@ defineMacro("\\lrcorner", "\\html@mathml{\\@lrcorner}{\\mathop{\\char\"231f}}");
 // \kern6\p@\hbox{.}\hbox{.}\hbox{.}}}
 // We'll call \varvdots, which gets a glyph from symbols.js.
 // The zero-width rule gets us an equivalent to the vertical 6pt kern.
-defineMacro("\\vdots",
-            "\\TextOrMath{\\textvdots}{{\\varvdots\\rule{0pt}{15pt}}}\\relax");
+defineMacro("\\vdots", "{\\varvdots\\rule{0pt}{15pt}}");
 defineMacro("\u22ee", "\\vdots");

 //////////////////////////////////////////////////////////////////////
diff --git a/src/symbols.js b/src/symbols.js
index 79f978a7..84086cd0 100644
--- a/src/symbols.js
+++ b/src/symbols.js
@@ -673,8 +673,9 @@ defineSymbol(text, main, inner, "\u2026", "\\ldots", true);
 defineSymbol(math, main, inner, "\u2026", "\\ldots", true);
 defineSymbol(math, main, inner, "\u22ef", "\\@cdots", true);
 defineSymbol(math, main, inner, "\u22f1", "\\ddots", true);
-defineSymbol(math, main, textord, "\u22ee", "\\varvdots"); // \vdots is a macro
-defineSymbol(text, main, textord, "\u22ee", "\\textvdots");
+// \vdots is a macro that uses one of these two symbols (with made-up names):
+defineSymbol(math, main, textord, "\u22ee", "\\varvdots");
+defineSymbol(text, main, textord, "\u22ee", "\\varvdots");
 defineSymbol(math, main, accent, "\u02ca", "\\acute");
 defineSymbol(math, main, accent, "\u02cb", "\\grave");
 defineSymbol(math, main, accent, "\u00a8", "\\ddot");
```

This stops us from introducing yet another command `\textvdots` when we already have `\varvdots` (which can work in both text and math mode), defines `\rule` to work in both text and math mode (as in LaTeX), and skips the unnecessary `\mathord`, so that we can use the same macro in text and math mode (just like LaTeX does).

**Comment by ronkok** [comment]
The code suggested by @edemaine looks good to me.

Since this enables a new feature, `\rule` in text mode, we should probably add a test. I suggest inserting:
```
    it("should parse in text mode", function() {
        expect(r`\text{a\rule{1em}{2em}b}`).toParse();
    });
```

after line 1067 of `test/katex-spec.js`.

**Comment by pzinn** [comment]
I don't think I can let you push to my branch. maybe it's a pro feature? can you instead make a PR?

**Comment by edemaine** [comment]
Replaced with #3997

**Pull request closed without merging**
