### PR TITLE
Release v0.10.1

### PR DESCRIPTION
**Pull request by ylemkimon**
v0.10.1 will be released from [v0.10.1-release](https://github.com/KaTeX/KaTeX/tree/v0.10.1-release), where `\includegraphics` has been reverted.

### CODE REVIEW

**Comment by edemaine** [comment]
Many thanks @ylemkimon!

**Comment by kevinbarabash** [comment]
Was there a bug in `\includegraphics`?

**Comment by kevinbarabash** [comment]
I see, it was to get a hot-fix out for the `\neq` issue.  I assume the concern around release `\includegraphics` is that we want to address the security concerns we had.

**Comment by edemaine** [comment]
@kevinbarabash Exactly. I think it would be dangerous to release `\includegraphics` until we have a `trust` (or similar, e.g. #1794) setting that lets people turn it off for untrusted inputs. Not as dangerous as `\cssId` or `\class`, but I think it's still a security issue.  It'd be great to get more feedback/review on #1794 (or another approach if that's preferred) so that releases become easier. 😄

**Pull request merged**
