### PR TITLE
test: update Firefox screenshots

### PR DESCRIPTION
**Pull request by ylemkimon**

### CODE REVIEW

**Comment by kevinbarabash** [comment]
What changed to require an update to the Firefox screenshots?

**Comment by kevinbarabash** [comment]
I'm guessing this is to fix the test failures on #2830.

**Review by kevinbarabash — APPROVED** [review]
All changes screenshots appear to be trivial.

**Comment by ylemkimon** [comment]
@kevinbarabash The Firefox version was updated in https://github.com/KaTeX/KaTeX/pull/2841, but it seems GitHub no longer runs the workflow updated in the pull request.

**Pull request merged**
