### PR TITLE
Update API language on auto-render script

### PR DESCRIPTION
**Pull request by xymostech**
I noticed that the docs said there were "two auto-render-specific keys" and then proceeded to list 5 extra keys that could be passed. :) I updated the language in all of the versions of docs because they were all incorrect.

I changed them all to say "several" so that this doesn't accidentally get out of date again when another key is added in the future, but I'm happy to change it to say "five"/"four" in the different versions if that seems better.

Also 👋

### CODE REVIEW

**Comment by csilvers** [comment]
Sadly I don't have write access, but I can at least respond to your commit message:

> Also wave

We miss you!

**Comment by edemaine** [comment]
It looks like the CircleCI tests aren't running, perhaps because only Markdown files changed, but Github won't let the PR merge without them (it says "Expected — Waiting for status to be reported"). @ylemkimon any ideas?

**Comment by edemaine** [comment]
> It looks like the CircleCI tests aren't running, perhaps because only Markdown files changed, but Github won't let the PR merge without them (it says "Expected — Waiting for status to be reported").

Seems to have just been transient -- merging master in caused the tests to actually run. Yay!

**Comment by ronkok** [comment]
@xymostech I just want to add my appreciation for the work you did during the creation of KaTeX. It's an awesome library.

**Comment by kevinbarabash** [comment]
@xymostech 👋 🙂

**Pull request merged**
