### PR TITLE
docs: Update \operatorname in supported_table.md 0.12.0

### PR DESCRIPTION
**Pull request by ronkok**

### CODE REVIEW

**Review by edemaine — APPROVED** [review]
Thanks!

**Comment by edemaine** [comment]
@ylemkimon Any idea why adding `test screenshots` label isn't getting the screenshotter to run here? It worked fine in #2570...

(It would also be great to not have to run screenshots when it's just documentation changes, like we do for other tests...)

**Comment by ronkok** [comment]
> Any idea why … ?

I created this PR differently than usual. I edited the file online, using the GitHub web editor. That may have something to do with it?

**Comment by ylemkimon** [comment]
The issue seems to be due to https://www.githubstatus.com/incidents/28js6274ybpb.

**Pull request merged**
