### PR TITLE
Release v0.10.2

### PR DESCRIPTION
**Pull request by kevinbarabash**
I didn't see any breaking changes so I did a point release.  This release contains lots of MathML improvements, a few new commands, as well as a fix for `\not` on Safari.

### CODE REVIEW

**Comment by edemaine** [comment]
@kevinbarabash We need to rollback `\includegraphics` in this release, until we fix the safety issue. @ylemkimon

**Comment by kevinbarabash** [comment]
@edemaine thanks for flagging this.

**Comment by ylemkimon** [comment]
Could you update the `CHANGELOG.md`?

**Comment by kevinbarabash** [comment]
Once #1951 lands I'm going to close this PR and open a new one along with updates to CHANGELOG.md.

**Comment by kevinbarabash** [comment]
This PR has been superseded by #1958.

**Pull request closed without merging**
