### PR TITLE
Added Android library

### PR DESCRIPTION
**Pull request by judemanutd**
Added a link to the android library for katex rendering.

### CODE REVIEW

**Comment by ylemkimon** [comment]
Please note that correct capitalization of the name is `KaTeX`, with capital `T` and `X`, just like `TeX`.

**Comment by judemanutd** [comment]
> Please note that correct capitalization of the name is `KaTeX`, with capital `T` and `X`, just like `TeX`.

@ylemkimon  Hey thanks for pointing that out, I'm a little confused as to where you would like me to change that, should I change that in the md file or the library name and description itself?

**Comment by judemanutd** [comment]
@ylemkimon made the changes, let me know if anything is out of order.

**Comment by ylemkimon** [comment]
[clabot:check]

**Comment by judemanutd** [comment]
[clabot:check]

**Pull request merged**
