### PR TITLE
fix: MathML for stretchy accents. #2990

### LINKED ISSUE #2990: \widehat mathml toNode error
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
A clear and concise description of what the bug is. If your installation is available on the web or you can provide a minimal repo or CodePen that reproduces the bug, please add the link to it.

**To Reproduce:**
1. Open https://katex.org/
2. Input `\widetilde{ABCD}\tilde{ABCD}` in the demo-input textarea
3. Press F12 open Chrome DevTools
4. Switch to Elements tab and focus on the 'katex-mathml' element

**Expected behavior:**
The expected mathml should be: 
```html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><semantics><mrow><mover accent="true"><mi>x</mi><mo stretchy="true">^</mo></mover><mover accent="true"><mi>x</mi><mo>^</mo></mover></mrow><annotation encoding="application/x-tex">\widehat{x}\hat{x}</annotation></semantics></math>
```

while, now it gets below:
```html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><semantics><mrow><mover accent="true"><mi>x</mi><mo stretchy="true">undefined</mo></mover><mover accent="true"><mi>x</mi><mo>^</mo></mover></mrow><annotation encoding="application/x-tex">\widehat{x}\hat{x}</annotation></semantics></math>
```

The **key** question is the `widehat` mathml render to an undefined textnode.

**Screenshots:**
image

**Environment (please complete the following information):**
 - KaTeX Version: [0.13.6]
 - Device: [Desktop]
 - OS: [Mac OS Catalina 10.15.7]
 - Browser: [Chrome]
 - Version: [90]

**Additional context:**
None

### PR DESCRIPTION
**Pull request by nfer**
fix make stretchyCodePoint to textNode bug.

### CODE REVIEW

**Review by ronkok — CHANGES_REQUESTED** [review]
@nfer, Thank you for fixing this. Your code is correct.

Next, we should add a regression test to prevent this from happening again. I suggest modifying the file at: `/KaTeX/test/katex-spec.js` … to include:

```
describe("A MathML builder", function() {
    it("should properly render stretchy accents", function() {
        const markup = buildMathML(tree, r`\widetilde{ABCD}`, defaultOptions).toMarkup();
        expect(markup).toContain('<mo stretchy="true">');
    }
}
```

**Comment by ronkok** [comment]
Oops. I spoke too soon. There are two other issues to fix:

1. The line you edited is now too long to pass the linter. Maximum length is 84 characters. Please edit.
2. It turns out that there is a snapshot which contains a stretchy accent. You will need to `run test:jest -u`.

**Comment by nfer** [comment]
>     it("should properly render stretchy accents", function() {
>         const markup = buildMathML(tree, r`\widetilde{ABCD}`, defaultOptions).toMarkup();
>         expect(markup).toContain('<mo stretchy="true">');
>     }

@ronkok I add below test code in katex.spec.js

```js
describe("A stretchy MathML builder", function() {
    it("should properly render stretchy accents", function() {
        const tex = `\widetilde{ABCD}`;
        const tree = getParsed(tex);
        const markup = buildMathML(tree, tex, defaultOptions).toMarkup();
        expect(markup).toContain('<mo stretchy="true">');
    });
});
```

It test faild with result:

```console
    Expected substring: "<mo stretchy=\"true\">"
    Received string:    "<span class=\"katex-mathml\"><math xmlns=\"http://www.w3.org/1998/Math/MathML\"><semantics><mrow><mi>w</mi><mi>i</mi><mi>d</mi><mi>e</mi><mi>t</mi><mi>i</mi><mi>l</mi><mi>d</mi><mi>e</mi><mrow><mi>A</mi><mi>B</mi><mi>C</mi><mi>D</mi></mrow></mrow><annotation encoding=\"application/x-tex\">widetilde{ABCD}</annotation></semantics></math></span>"
```

It also failed with simple tex like `\tilde{ABCD}`. I think the question is on the `toMarkup()` function implement is not correct like `toNode()`. In my opinion, changes with `toMarkup()` should be another PR.

**Comment by ronkok** [comment]
You need to escape the backslash in the JS string. 

```
const tex = `\\widetilde{ABCD}`;
```

**Comment by nfer** [comment]
> You need to escape the backslash in the JS string.
> 
> ```
> const tex = `\\widetilde{ABCD}`;
> ```

Thanks. It works.

```js
describe("A stretchy MathML builder", function() {
    it("should properly render stretchy accents", function() {
        const tex = `\\widetilde{ABCD}`;
        const tree = getParsed(tex);
        const markup = buildMathML(tree, tex, defaultOptions).toMarkup();
        expect(markup).toContain('<mo stretchy="true">~</mo>');
    });
});
```

This test case failed in master, but works in pr branch.

Another question, should I add more test case, like widehat widecheck or utilde, or just `\\widetilde{ABCD}` is OK?

**Comment by ronkok** [comment]
I think just `\widetilde` is enough.

**Comment by nfer** [comment]
> Oops. I spoke too soon. There are three other issues to fix:
> 
> 1. The line you edited is now too long to pass the linter. Maximum length is 84 characters. Please edit.
> 2. It turns out that there is a snapshot which contains a stretchy accent. You will need to `run test:jest -u`.
> 3. Having made this change, you'll need to edit lines 57 - 59 and remove the first character. The resulting lines should be:
> 
> ```
>     "\\cdrightarrow": "\u2192",
>     "\\cdleftarrow": "\u2190",
>     "\\cdlongequal": "=",
> ```

I run `test:jest -u` with the latest code, but the snap file has nothing changed. Please help to check is any thing wrong or need add more test cases?

**Comment by ronkok** [comment]
The code looks good to me. I'll run the workflow and we'll see what we get.

**Review by ronkok — APPROVED** [review]
@nfer This looks great! Thank you for fixing this.

**Comment by nfer** [comment]
Thanks ronkok. I am glad to do something to improve Katex. :)

**Pull request merged**
