### PR TITLE
fix: Update Safari screenshot.

### PR DESCRIPTION
**Pull request by ronkok**
Two pending PRs are failing because Screenshotter does not like a particular Safari image. This PR adopts the preferred image in hopes that this will enable the other two PRs to pass.

### CODE REVIEW

**Comment by ronkok** [comment]
No good. It was worth a try.

**Comment by edemaine** [comment]
@ronkok I find that I just have to rerun the screenshotter tests one or two times before the Safari tests pass. ☹️

**Comment by ronkok** [comment]
How do I force screenshotter to rerun?

**Comment by ronkok** [comment]
Ah, I now see the rerun button. Thanks for the tip.

**Pull request closed without merging**
