### PR TITLE
Prevent tag overlaps

### PR DESCRIPTION
**Pull request by ronkok**
Prevent a `\tag` or an equation number from overlapping a long equation. This PR renders display mode using flexbox CSS. Glue elements are written to set the equation element and the tag element in their proper position.

Addresses issues #1983 & #2322.

### CODE REVIEW

**Comment by ronkok** [comment]
Oops. There are glitches. This is not yet ready for review.

**Comment by ronkok** [comment]
This is now ready for review. Here's a sample output of a long equation with a tag:

tag

Note that the equation is not centered on the page. It is centered on the section not occupied by the tag. I tried to center it on the page, but this is the best I could do. I think this is still a win. There will be no overlaps.

**Comment by ylemkimon** [comment]
Wouldn't this result in different location of equations. if those with numbers and those without numbers are mixed?

**Comment by ronkok** [comment]
> Wouldn't this result in different location of equations. if those with numbers and those without numbers are mixed?

Not if they were in the same environment. But otherwise, yes. That's bad, I suppose.

**Comment by ylemkimon** [comment]
LaTeX pushes the tag to the next line, if the equation overflows:
image

Would it be possible to implement this behavior?

**Comment by edemaine** [comment]
FYI, I investigated these options a lot when first implementing `\tag`; see #1309 and https://github.com/KaTeX/KaTeX/issues/899#issuecomment-335532235 (and other discussion in #899). My conclusion at that time was that it isn't possible to get all three desired properties:
1. Proper centering of equation
2. Tag on next line instead of overlapping
3. Proper vertical alignment with baseline

We already have the issue that (like LaTeX) display equations aren't responsive, so I figured giving up on (2) wasn't so bad. But I can imagine it's bad if you allow horizontal scrolling, say. I believe this PR gives up (1).

I do wonder about returning to the float approach. If we leave in the strut hack that's currently in KaTeX, perhaps we'd just give up (3) in the case of long equations, but that's probably better than overlap?

**Comment by ronkok** [comment]
I'll open a different PR and implement a float. Then we can choose which one we prefer.

**Pull request closed without merging**
