### PR TITLE
Support double-square curly braces

### PR DESCRIPTION
**Pull request by ice1000**
Signed-off-by: ice1000 <ice1000kotlin@foxmail.com>

Addressed my own comment: https://github.com/KaTeX/KaTeX/pull/1947#issuecomment-485986880

### CODE REVIEW

**Comment by ice1000** [comment]
Use this code to preview on your website:

```
\mathopen{\{\mkern-3.2mu[}
i
\mathclose{]\mkern-3.2mu\}}
```

**Comment by ronkok** [comment]
@ice1000 Can you go in and resolve the merge conflicts?

**Comment by ice1000** [comment]
> @ice1000 Can you go in and resolve the merge conflicts?

Sure, done.

**Comment by ice1000** [comment]
@ronkok CI passed, please take a look.

**Comment by ronkok** [comment]
@ice1000 Three comments:

1. I can find no LaTeX packages with a function named `\llbrace` or `\rrbrace`. But the `stix` package contains `\lBrace` and `\rBrace`. Those would be better choices for the names of these functions.

2. KaTeX produces both HTML and MathML and getting a macro to do each one well gets a little tricky. @edemaine has written a KaTeX-only macro syntax that enables good HTML and good MathML in the same macro. The syntax is your case would be `defineMacro("\\lBrace", \\html@mathml{<HTML code>}{<MathML code>});` You have already written good HTML code. But in MathML you can't be sure what font will be used, so you have to call the Unicode character. And it helps to use the `\char` function so that the macro does not expand in an infinite loop. So it ends up as: ``defineMacro("\\lBrace", \\html@mathml{"\\mathopen{\\{\\mkern-3.2mu[}}{"\\mathopen{\\char`\u2983});``

3. Do you want to try writing macros for characters `⦃` and `⦄` that expand to  `\lBrace` and `\rBrace`?

**Comment by ice1000** [comment]
> I can find no LaTeX packages with a function named `\llbrace` or `\rrbrace`. But the stix package contains `\lBrace` and `\rBrace`.

Well yeah, I've done the same investigation and got the same results prior to PRing kAtEx. My motivation of using `\llbrace` is that it's more consistent with another function, `\llbracket`.
I'll change it to `\lBrace`.

> KaTeX produces both HTM ...

Got it! Will do.

> Do you want to try writing...

Yeah! Is that simply aliasing the macro?

**Comment by ronkok** [comment]
Yep.

**Comment by ice1000** [comment]
Addressed comments, please retake a look

**Comment by ice1000** [comment]
I've observed that PRs in this repo are all squashed when merging, I'm assuming that it's Ok of merge master/creating small commits instead of rebasing on master and always commit by amending the previous one.

**Comment by ronkok** [comment]
@ice1000 Can you also add to the documentation in `docs/support_table.md`?

**Comment by ice1000** [comment]
> @ice1000 Can you also add to the documentation in `docs/support_table.md`?

Done

**Comment by ronkok** [comment]
@ice1000 Thank you for this PR. It's a nice addition to KaTeX.

**Comment by ice1000** [comment]
You're welcome!

**Comment by ylemkimon** [comment]
[clabot:check]

**Comment by ice1000** [comment]
[clabot:check]

**Pull request merged**
