### PR TITLE
fix(fonts): correct width of \cong glyph, fix \boldsymbol{\cong}

### LINKED ISSUE #2199: `\cong` has extra trailing space
The `\cong` relation, ≅, has some extra trailing space compared with `\cong` in official LaTeX and other similar relations in KaTeX.

```latex
\begin{aligned}
  & x \equiv x \\
  & x \cong x \\
  & x \approxeq x \\
\end{aligned}
```

[Live demo](https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22trust%22%3Afalse%2C%22code%22%3A%22%5C%5Cbegin%7Baligned%7D%5Cn%20%20%26%20x%20%5C%5Cequiv%20x%20%5C%5C%5C%5C%5Cn%20%20%26%20x%20%5C%5Ccong%20x%20%5C%5C%5C%5C%5Cn%20%20%26%20x%20%5C%5Capproxeq%20x%20%5C%5C%5C%5C%5Cn%5C%5Cend%7Baligned%7D%22%7D)

KaTeX rendering:
cong-katex

QuickLaTeX rendering:
cong-quicklatex

 - KaTeX Version: 0.11.1
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79

### PR DESCRIPTION
**Pull request by edemaine**
~~This PR is currently based on #2866 for build purposes.  I'll rebase once #2866 is merged.~~ Rebased.

**What is the previous behavior before this PR?**
`\cong` had the default advanceWidth of 1000

**What is the new behavior after this PR?**
`\cong` has the correct advanceWidth, matching `=` that it's based on (and many other binary operators).

Fixes #2199

image

### CODE REVIEW

**Review by ylemkimon — DISMISSED** [review]

**Comment by edemaine** [comment]
Hmm, there seems to be something wrong with the fonts now: the space has gotten bigger:

image

@ylemkimon Any ideas? I thought the fonts were maybe not updated, but I see you just updated them.

**Comment by ylemkimon** [comment]
I wonder we should fix the date of fonts to a specific date in the past. Currently, a change in a font requires updating all the fonts.

**Comment by edemaine** [comment]
I found a fix.  Patch incoming.

**Comment by edemaine** [comment]
Here's a screenshot of the fixed version:

image

```latex
x\cong y\\
x = y \\
x \boldsymbol {\cong} y \\
x \boldsymbol {=} y \\
```

**Comment by edemaine** [comment]
@ylemkimon I updated this to use the new font versioning. Would you be able to review it (again)?

Here's a demo from the Netlify build:

image

**Review by ylemkimon — APPROVED** [review]
Thank you for fixing this and sorry for the delayed review.

**Pull request merged**
