### PR TITLE
Add detail about colorbox third text parameter

### PR DESCRIPTION
**Pull request by qcho**
As stated in issue #1766

### CODE REVIEW

**Comment by qcho** [comment]
[clabot:check]

**Comment by qcho** [comment]
Wording is perfect now! No further changes seem necessary.

I see what you mean with `remarkable-katex` and it's `braceLevel` issue. Hope it gets fixed soon by the maintainer. 

If that doesn't happen:
1. you may change the configuration of it `{delimiter: '$'}` for other one in the Katex documentation and avoid the problem alltoguether.
2. maybe you or me or someone can send the PR to `remarkable-katex`. We'll see :)

**Comment by bradhowes** [comment]
Hi everyone. Developer for the remarkable-katex plugin. Thanks for raising the issue. I've implemented a fix and my test case ` mdWithDollar.render('Equation $\\colorbox{aqua}{$F=ma$}$.')` passes. I've pushed a new version 1.1.5. Please let me know if there are still issues.

**Comment by edemaine** [comment]
@bradhowes Wow, that was fast! Thanks for taking that on and fixing!

I just pushed a new version and https://deploy-preview-2280--katex.netlify.app/docs/next/supported.html#style-color-size-and-font now looks good to me. If someone (@ronkok?) could spot check the rest to make sure there aren't any new issues, that would be appreciated.

@ylemkimon I changed the way that `remarkable-katex` is embedded, ignoring it in `.eslintignore` instead of changing its style to conform to ours, so it's easier to upgrade in the future. (I tried to use it as an NPM package, but I see the issue is that we need to `require("../..")` instead of `require("katex")`.) Let me know if you disagree with that approach / have a better idea!

**Pull request merged**
