### PR TITLE
fix: Use SVGs for some stacked delims

### PR DESCRIPTION
**Pull request by ronkok**
This PR uses a single SVG to render certain stretchy delimiters that have until now been rendered using a stack of font glyphs. The browser's imprecision in span placement is thus evaded.

The delimiters thus treated are: `\lparen`, `\rparen`, `\brack`, `\rbrack`, `\vert`, `\Vert`, `\lfloor`, `\rfloor`, `\lceil`, and `\rceil`, along with all the other functions that call the same stretchy delimiters.

Resolves issues #3650 and #3168.

### CODE REVIEW

**Comment by ronkok** [comment]
I'll fix the screenshotter pics tomorrow.

**Comment by ronkok** [comment]
@edemaine This PR is now ready for review. Since it is a purely visual effort, the best way to review it may be by looking at the  screenshotter diffs for commit https://github.com/KaTeX/KaTeX/pull/3686/commits/ae407cf39ddf3e5b043e6365f707f0c06ee774b1. The final commit just used those images to replace the earlier ones, so it is checking against itself and won't tell you anything.

**Comment by edemaine** [comment]
@ronkok This sounds awesome! Thanks for working on this long-standing issue.

Am I reading the screenshot diffs correctly that `|` now has butt line caps, whereas before they were round line caps? It seems like in LaTeX they are supposed to be round line caps:

image

[QuickLaTeX rendering]

(Admittedly a very small difference!)

**Comment by ronkok** [comment]
Re: butt line caps. You are correct. That's just sloth on my part. I can take a few minutes and create a radius.

**Comment by ronkok** [comment]
Line caps are rounded. Screenshots are refreshed. This PR should be ready to go.

**Comment by ronkok** [comment]
This is a friendly reminder that this PR is ready for review and it resolves a long-standing issue.

**Comment by edemaine** [comment]
Sorry, I haven't forgotten; it's just been a busy time. I will try to review next week, but if not, should definitely have time the following week.

**Review by ylemkimon — APPROVED** [review]

**Comment by ylemkimon** [comment]
Thank you for the PR! I wonder whether we can get rid of these glyphs.

**Comment by edemaine** [comment]
Thanks @ylemkimon!!

If you have additional time, it'd be great to get your PR #3385 revised, as we recently had a request for `\ifmmode`, which would be easy to add along with `\if@display`. (If you don't have time, though, I'll revise it eventually.)

**Pull request merged**
