### PR TITLE
docs: add new user link

### PR DESCRIPTION
**Pull request by kim-tom**
Hi, I made the website which uses KaTeX. This is the math-specified blog site.
But I' m not sure how to add users in the KaTeX documentation.
Is this correct??

### CODE REVIEW

**Comment by ylemkimon** [comment]
[clabot:check]

**Comment by ylemkimon** [comment]
[clabot:check]

**Comment by ylemkimon** [comment]
Thank you for the PR! Did you sign the CLA?

**Comment by kim-tom** [comment]
[clabot:check]

**Comment by kim-tom** [comment]
> Hey @kim-tom,
> 
> Thanks for the PR! Mind signing our [Contributor License Agreement](http://khanacademy.org/r/cla)?
> 
> When you've done so, go ahead and comment `[clabot:check]` and I'll check again.
> 
> Yours truly,
> khanbot

[clabot:check]

**Comment by kim-tom** [comment]
@khanbot 
[clabot:check]

**Comment by kim-tom** [comment]
Hi, @ylemkimon 
I singned the CLA. 
Could you tell me where should I comment `[clabot:check]`??
This is my first commit.

**Comment by ylemkimon** [comment]
No worries :smile: Currently, the bot is down so it wouldn't work.

**Review by ylemkimon — APPROVED** [review]

**Comment by kim-tom** [comment]
Thank you!
I wish I can make more important commit someday😄

**Pull request merged**
