### PR TITLE
Fix \\ and \newline after operator

### LINKED ISSUE #1790: Hard newline, \\,  fails after relation
A hard newline, `\\,` will properly insert a newline after an ORD atom, as in `M = a \\ b`. But the hard newline is ignored if it follows a relation, as in `M = \\ a`.

LaTeX will insert the newline in either case.

### PR DESCRIPTION
**Pull request by edemaine**
Fix #1790.  `\\` and `\newline` render as a span with classes `mspace` and `newline`.  We need to check for `newline` when bringing spaces into the same `base` group.

### CODE REVIEW

**Comment by edemaine** [comment]
Agreed.  Added tests!  I confirmed that the new tests do not succeed with the old code.

**Comment by kevinbarabash** [comment]
For some reason the Chrome tests are failing with:
```
Error response from daemon: error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"
```
@edemaine are the Chrome tests failing for you locally?

**Comment by kevinbarabash** [comment]
I'm seeing the following error with the Chrome tests:
```
Error response from daemon: error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"
```
@edemaine are the Chrome tests failing for you locally?

**Comment by edemaine** [comment]
@kevinbarabash I just checked and the screenshot tests pass locally.

Could this have something to do with the move to the KaTeX organization?  I haven't changed anything on my side, but maybe I should have (and given that it's affecting me only...).  I tried to log into CircleCI to rerun the tests here, and CircleCI won't let me / gets confused (oddly, I get a 404 error), despite this working on your PR...

**Comment by edemaine** [comment]
Did anyone do anything? Seems to be working now! Weird.

**Comment by kevinbarabash** [comment]
I didn't do anything.  I'm glad to see things are working now.

**Pull request merged**
