### PR TITLE
chore: move test fonts to the main repo

### PR DESCRIPTION
**Pull request by ylemkimon**
A step toward #1411 and to remove submodules.

This migrates https://github.com/KaTeX/katex-test-fonts to the main repo.

Git is able to easily handle binary files ~10 MB and test fonts are not likely to change.

### CODE REVIEW

**Review by kevinbarabash — APPROVED** [review]
LGTM.  This should make it easier for other contributors in the future.

**Comment by pzinn** [comment]
I'm a bit late to the party, but how are we supposed to recompile fonts with the new set-up?

**Comment by ylemkimon** [comment]
@pzinn Run `dockers/fonts/buildFonts.sh` (Docker is required). Note the relevant PR is #2837.

**Comment by pzinn** [comment]
thanks. doesn't obviously work:
```
pzinn@mammoth - ~/KaTeX/dockers/fonts ./buildFonts.sh 
./Dockerfile: No such file or directory
~/KaTeX/src ~/KaTeX
~/KaTeX
Need to build docker image katex/fonts:DF-
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/pzinn/KaTeX/Dockerfile: no such file or directory
````

**Pull request merged**
