### PR TITLE
Fix \Rho

### LINKED ISSUE #1869: Incorrect glyph for greek letter capital rho "Ρ"
Uppercase of "ρ" (rho) should be "Ρ" instead of "R".

screenshot from 2019-03-07 18-36-09

Meanwhile, this letter is not included in the table of Greek letters in KaTeX document (<https://katex.org/docs/supported.html#letters-and-unicode>).

### PR DESCRIPTION
**Pull request by riteme**
Fixes #1869.

### CODE REVIEW

**Comment by ice1000** [comment]
This is really a critical bug!

**Comment by ylemkimon** [comment]
[clabot:check]

**Comment by riteme** [comment]
[clabot:check]

**Comment by ylemkimon** [comment]
[clabot:check]

**Comment by ylemkimon** [comment]
@riteme It seems the GitHub username was entered incorrectly.

**Comment by riteme** [comment]
[clabot:check]

**Pull request merged**
